version: '3'
services:
  my_end_py:
    build: 
      context: ./flask_s/
      dockerfile: Dockerfile
    container_name: flask_myend_${NODETYPE}
    command: sh run.sh
    ports:
      - "31002:31001"
    volumes:
      - ./flask_s/:/py_end
