version: '3'
services:
  my_end_py:
    build: 
      context: ./flask_s/
      dockerfile: Dockerfile
    container_name: flask_myend_${NODETYPE}
    command: sh run.sh
    environment:
      - NODETYPE=${NODETYPE}
    # env_file:
    #   - ${NODETYPE}.env
    ports:
      - "31002:31001"
    volumes:
      - ./flask_s/:/py_end
    depends_on:
      - mongodb
    links:
      - mongodb:mongodb
  mongodb:
    image: mongo
    container_name: mongodb
    # environment:
    #   - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
    #   - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    #   - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
    #   - MONGO_INITDB_USER=${MONGO_INITDB_USER}
    #   - MONGO_INITDB_PASSWORD=${MONGO_INITDB_PASSWORD}
    ports:
      - "27017:27017"
    volumes:
      - ./mongo_data:/data/
      - ./mongo_conf:/etc/mongodb/
      - ./mongo_db:/data/db/






    