# 如果需要从新构建 dockerfile > docker-compose down -v;docker-compose up --build
version: '3'
services:
  y_end_py:
    build:
      context: ./flask_s/
      dockerfile: ./Dockerfile
    container_name: flask_myend_${NODETYPE}
    # command: python app.py  # 覆盖DOCKERFILE 的cmd
    restart: always
    environment:
      - TZ=Asia/Shanghai
      - NODETYPE=${NODETYPE}
      - MONGODB_PWD=${MONGODB_PWD}
    ports:
      - "31002:31001"
    volumes:
      - ./flask_s/:/py_end
    depends_on:
      - y_end_mongodb 
    links:
      - y_end_mongodb:y_end_mongodb

  y_end_mongodb:
    image: mongo
    container_name: y_end_mongodb
    restart: always
    ports:
      - 27020:27017
    volumes:
      - ./mongo/mongo_data:/data/
      - ./mongo/mongo_conf:/etc/mongodb/
      - ./mongo/mongo_db:/data/db/
    environment:
      TZ: Asia/Shanghai
      MONGO_INITDB_ROOT_USERNAME: root
      # MONGO_INITDB_ROOT_PASSWORD: "xx12345xxx"
      # mongodb_pwd
      # MONGODB_PWD
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PWD:-mongodb_pwd1234}
    command: mongod --directoryperdb --port 27017
